before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev libboost-program-options-dev
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-graph-dev
  - sudo apt-get install -y libboost-regex-dev
  - sudo apt-get install -y libz-dev
  - sudo apt-get install -y libpthread-stubs0-dev
env:
  - CRONO_HOME=$PWD BOOST_ROOT=/usr/include/boost
language: c++
compiler:
  - g++
script:
  - make
notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - masab.ahmad@uconn.edu
